
echo "aliases.sh 🌈" | lolcat

alias cd='cd && ls -a'
alias md='mkdir -pv'
alias ll='lsd -a --group-dirs first'
alias cp='cp -irf'
alias mv='mv -ivnf'
alias rmf='rm -irf'
alias chmd='chmod +x'
alias pkgup='pkg update && pkg upgrade && pkg autoclean -y'
alias aptup='apt-get update && apt-get  upgrade && apt-get dist-upgrade && apt-get autoclean && apt-get autoremove -y' 
alias src='soirce ~/.bashrc'
alias vrc='vi .bashrc'
alias zrc='vi .zshrc'
alias srz='source ~/.zshrc'
alias sra='source ~/aliases.sh'
alias vra='vi aliases.sh'
alias srp='source .bash_profile'
alias vrp='vi .bash_profile'
alias vrf='vi .bash_functions'
alias vrg='vi .bash_config'
alias c='clear'
alias vr=' vi .vimrc'
alias apti='apt install'
alias apts='apt search'
alias aptre='apt reinstall'
alias aptr='apt remoce'
alias atg='apt-get install'
alias h='htop'
alias junk='mv --force $1 ~/.local/share/Trash'
alias t='touch'
alias sr='source'
alias tcn='mv --force -t ~/.local/share/Trash '
alias nano='/usr/bin/nano -EMWacuw$ --tabsize=4'
alias note='cd ~; cd notes; ls -a; sleep 10; vi'
alias cpv='rsync -ah --info=progress2'
alias rm='rm -Iv --preserve-root'
alias count='find . -type f | wc -l'
alias fastping='ping -c 100 -s.2'
alias diff='colordiff'
alias gh='history|grep'
alias ports='netstat -tulanp'
alias wget='wget -c'
alias v='vim'
alias now='date +"%T"'
alias ve='python3 -m venv ./venv'
alias e='exit'
alias grep='grep -E'

